### ISSUE TITLE
add information on the transcription convention?

### ISSUE THREAD

**Issue by tillgrallert** [digitalottoman/vocabularies#1]
Has IANA a way to record the transcription convention used to render a language in an uncommon script?
In [BCP 47](https://tools.ietf.org/html/bcp47) the language code is followed by the code for the script is followed by the transcription system. Examples would be:
- ar-Latn-EN: Arabic transcribed in to Latin characters following common English patterns
- ar-Latn-FR: the same following French conventions
- ar-Latn-x-ijmes: the same following the IJMES convention

**Comment by whanley** [comment]
This is a good idea. We'll add a list to our vocab, and transfer them to a document here.
